# Generated by Django 5.2.17 on 2026-10-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationlog',
            name='unique_reminder_notification',
        ),
    ]
