# Generated by Django 5.2.17 on 2026-09-26 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0005_cattledetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_type', models.CharField(choices=[('general', 'General'), ('medical', 'Medical'), ('appointment', 'Appointment'), ('feed', 'Feed / Supplies'), ('other', 'Other')], default='general', max_length=30)),
                ('due_date', models.DateField()),
                ('recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='animals.animal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('general', 'General'), ('exam', 'Exam'), ('vaccination', 'Vaccination'), ('medication', 'Medication'), ('injury', 'Injury'), ('surgery', 'Surgery'), ('dental', 'Dental'), ('lab', 'Lab/Test'), ('deworming', 'Deworming'), ('other', 'Other')], max_length=30)),
                ('create_record_on_completion', models.BooleanField(default=True)),
                ('reminder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_config', to='reminders.reminder')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder_completions', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='reminders.reminder')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
