# Generated by Django 5.2.17 on 2026-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remindercompletion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
