# Generated by Django 5.2.17 on 2026-10-09 11:27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def check_legacy_prices(apps, schema_editor):
    Listing = apps.get_model("marketplace", "SaleListing")
    if Listing.objects.using(schema_editor.connection.alias).filter(price__lt=0).exists():
        raise RuntimeError("Negative legacy listing prices must be reviewed before this migration; no prices were modified.")


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animalaccess_can_manage_training'),
        ('marketplace', '0001_initial'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_legacy_prices, migrations.RunPython.noop),
        migrations.AddField(
            model_name='salelisting',
            name='actual_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='sale_listings', to='media_library.animalmedia'),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='salelisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='salelisting',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='listing_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salelisting',
            constraint=models.CheckConstraint(condition=models.Q(('actual_sale_price__gte', 0), ('actual_sale_price__isnull', True), _connector='OR'), name='listing_actual_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salelisting',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['available', 'pending', 'sold'])), name='listing_valid_status'),
        ),
    ]
