# Generated by Django 5.2.17 on 2026-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_salelisting_actual_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinquiry',
            name='admin_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='saleinquiry',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='saleinquiry',
            name='delivery_state',
            field=models.CharField(choices=[('legacy', 'Legacy (delivery unknown)'), ('pending', 'Pending notification'), ('sending', 'Notification started (review if stalled)'), ('sent', 'Both email sends acknowledged'), ('needs_review', 'Notification needs review')], default='legacy', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='saleinquiry',
            name='notification_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='saleinquiry',
            name='submission_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='saleinquiry',
            constraint=models.UniqueConstraint(fields=('listing', 'submission_key'), name='unique_listing_inquiry_submission'),
        ),
    ]
