# Generated by Django 5.2.17 on 2026-10-04 16:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0006_animalaccess_can_manage_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('assessment_criteria', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('location_name', models.CharField(blank=True, help_text='One-off location or historical location name.', max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('ride_type', models.CharField(choices=[('trail', 'Trail'), ('arena', 'Arena'), ('road', 'Road'), ('lesson', 'Lesson'), ('conditioning', 'Conditioning'), ('event', 'Competition / event'), ('other', 'Other')], default='trail', max_length=30)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('route', models.TextField(blank=True)),
                ('terrain', models.CharField(blank=True, max_length=250)),
                ('weather', models.CharField(blank=True, max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at', '-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('animal', models.ForeignKey(limit_choices_to={'species': 'horse'}, on_delete=django.db.models.deletion.PROTECT, related_name='ride_participations', to='animals.animal')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.ride')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='animals',
            field=models.ManyToManyField(related_name='rides', through='training.RideParticipant', to='animals.animal'),
        ),
        migrations.CreateModel(
            name='RidingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='training.ridinglocation'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('location_name', models.CharField(blank=True, help_text='One-off location or historical location name.', max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('trainer_name', models.CharField(blank=True, max_length=150)),
                ('session_type', models.CharField(choices=[('groundwork', 'Groundwork'), ('round_pen', 'Round pen'), ('desensitization', 'Desensitization'), ('mounted', 'Mounted training'), ('trailer', 'Trailer loading'), ('handling', 'Handling / hoof care'), ('obstacles', 'Obstacles'), ('conditioning', 'Conditioning'), ('journal', 'Historical journal note'), ('other', 'Other')], default='groundwork', max_length=30)),
                ('goals', models.TextField(blank=True)),
                ('successes', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('animal', models.ForeignKey(limit_choices_to={'species': 'horse'}, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='animals.animal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='training.ridinglocation')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='training.ride')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at', '-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency', models.CharField(blank=True, choices=[('needs_work', 'Needs work'), ('introduced', 'Introduced'), ('learning', 'Learning'), ('improving', 'Improving'), ('reliable', 'Reliable'), ('mastered', 'Mastered')], help_text='Blank means practiced without an assessment.', max_length=20)),
                ('context', models.CharField(blank=True, help_text='For example left side, right side, or mounted.', max_length=100)),
                ('accomplishment', models.CharField(blank=True, max_length=250)),
                ('evidence', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='training.trainingsession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='training.trainingskill')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='rideparticipant',
            constraint=models.UniqueConstraint(fields=('ride', 'animal'), name='unique_ride_animal'),
        ),
        migrations.AddConstraint(
            model_name='rideparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gt', 0), _connector='OR'), name='participant_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='rideparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('distance_miles__isnull', True), ('distance_miles__gte', 0), _connector='OR'), name='participant_nonnegative_distance'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('distance_miles__isnull', True), ('distance_miles__gte', 0), _connector='OR'), name='ride_nonnegative_distance'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gt', 0), _connector='OR'), name='ride_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gt', 0), _connector='OR'), name='training_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='sessionskillprogress',
            constraint=models.UniqueConstraint(fields=('session', 'skill', 'context'), name='unique_session_skill_context'),
        ),
    ]
