# Generated by Django 5.2.17 on 2026-10-08 11:12

from django.db import migrations, models


def preserve_established_skills(apps, schema_editor):
    progress = apps.get_model("training", "SessionSkillProgress")
    progress.objects.using(schema_editor.connection.alias).filter(proficiency__in=["reliable", "mastered"]).update(accomplished=True)


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_foundation_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionskillprogress',
            name='accomplished',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_established_skills, migrations.RunPython.noop),
    ]
