# Generated by Django 5.2.17 on 2026-10-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animalaccess_can_manage_training'),
        ('training', '0003_sessionskillprogress_accomplished'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_skill_progress', to='animals.animal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='training.ride')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_observations', to='training.trainingskill')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('ride', 'animal', 'skill'), name='unique_ride_animal_skill')],
            },
        ),
    ]
