# Generated by Django 5.2.17 on 2026-09-19 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('general', 'General'), ('exam', 'Exam'), ('vaccination', 'Vaccination'), ('medication', 'Medication'), ('injury', 'Injury'), ('surgery', 'Surgery'), ('dental', 'Dental'), ('lab', 'Lab/Test'), ('deworming', 'Deworming'), ('other', 'Other')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('veterinarian', models.CharField(blank=True, max_length=200)),
                ('clinic', models.CharField(blank=True, max_length=200)),
                ('medication', models.CharField(blank=True, max_length=250)),
                ('dosage', models.CharField(blank=True, max_length=150)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('private_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='animals.animal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
