# Generated by Django 5.2.17 on 2026-09-19 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('species', models.CharField(choices=[('horse', 'Horse'), ('dog', 'Dog'), ('cattle', 'Cattle'), ('other', 'Other')], max_length=30)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in pounds.', max_digits=7, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('inactive', 'Inactive'), ('other', 'Other')], default='active', max_length=30)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('caretaker', 'Caretaker'), ('trainer', 'Trainer'), ('vet', 'Veterinarian'), ('viewer', 'Viewer')], max_length=30)),
                ('can_edit_profile', models.BooleanField(default=False)),
                ('can_manage_medical', models.BooleanField(default=False)),
                ('can_manage_appointments', models.BooleanField(default=False)),
                ('can_upload_media', models.BooleanField(default=False)),
                ('can_manage_documents', models.BooleanField(default=False)),
                ('can_manage_access', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal Access',
                'verbose_name_plural': 'Animal Access',
            },
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HorseBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('registration_number', models.CharField(blank=True, max_length=150)),
                ('microchip_number', models.CharField(blank=True, max_length=100)),
                ('rabies_tag_number', models.CharField(blank=True, max_length=100)),
                ('spayed_neutered', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            bases=('animals.animal',),
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('foal_year', models.IntegerField(blank=True, editable=False, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='BLM Brand')),
                ('herd_management_area', models.CharField(blank=True, max_length=100)),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in hands.', max_digits=5, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=150)),
                ('breed_registry', models.CharField(blank=True, max_length=150)),
                ('sire', models.CharField(blank=True, max_length=150)),
                ('dam', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
            ],
            bases=('animals.animal',),
        ),
    ]
