# Generated by Django 5.2.17 on 2026-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
