# Generated by Django 5.2.17 on 2026-09-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in hands.', max_digits=3, null=True),
        ),
    ]
