# Generated by Django 5.2.17 on 2026-09-21 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_horse_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleDetails',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
                ('breed', models.CharField(blank=True, max_length=150)),
                ('registration_number', models.CharField(blank=True, max_length=150)),
                ('ear_tag', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('sire', models.CharField(blank=True, max_length=150)),
                ('dam', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cattle Details',
                'verbose_name_plural': 'Cattle Details',
            },
            bases=('animals.animal',),
        ),
    ]
