# Generated by Django 5.2.17 on 2026-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_cattledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalaccess',
            name='can_manage_training',
            field=models.BooleanField(default=False),
        ),
    ]
